apiVersion: v1
kind: Service
metadata:
  name: user-server
  namespace: simple-living
  annotations:
    simple-living.io/internal-dns: "user-server.simple-living.svc.cluster.local"
spec:
  type: ClusterIP
  selector:
    app: user-server
  ports:
    - name: grpc
      protocol: TCP
      port: 9101
      targetPort: 9101
