// GENERATED by tools/generate_brpc_stub_server.py — replace with real logic.
// tracking-domain
#include <gflags/gflags.h>
#include <brpc/server.h>
#include <butil/logging.h>

#include "tracking_domain.pb.h"

DEFINE_int32(port, 9105, "TCP port for this brpc server");

namespace simple_living {
namespace tracking_domain {

class TrackingLinkServiceImpl : public TrackingLinkService {
public:
    void AssembleTrackingLink(::google::protobuf::RpcController* controller,
              const AssembleTrackingLinkRequest* request,
              AssembleTrackingLinkResponse* response,
              ::google::protobuf::Closure* done) override {
        brpc::ClosureGuard done_guard(done);
        (void)controller;
        (void)request;
        (void)response;
    }

};

class TrackingRedirectServiceImpl : public TrackingRedirectService {
public:
    void ResolveRedirect(::google::protobuf::RpcController* controller,
              const ResolveRedirectRequest* request,
              ResolveRedirectResponse* response,
              ::google::protobuf::Closure* done) override {
        brpc::ClosureGuard done_guard(done);
        (void)controller;
        (void)request;
        (void)response;
    }

};

class TrackingClickServiceImpl : public TrackingClickService {
public:
    void AckClick(::google::protobuf::RpcController* controller,
              const AckClickRequest* request,
              AckClickResponse* response,
              ::google::protobuf::Closure* done) override {
        brpc::ClosureGuard done_guard(done);
        (void)controller;
        (void)request;
        (void)response;
    }

};

class TrackingConversionServiceImpl : public TrackingConversionService {
public:
    void IngestConversion(::google::protobuf::RpcController* controller,
              const IngestConversionRequest* request,
              IngestConversionResponse* response,
              ::google::protobuf::Closure* done) override {
        brpc::ClosureGuard done_guard(done);
        (void)controller;
        (void)request;
        (void)response;
    }

};

class TrackingCommissionViewServiceImpl : public TrackingCommissionViewService {
public:
    void GetCommissionSummary(::google::protobuf::RpcController* controller,
              const GetCommissionSummaryRequest* request,
              GetCommissionSummaryResponse* response,
              ::google::protobuf::Closure* done) override {
        brpc::ClosureGuard done_guard(done);
        (void)controller;
        (void)request;
        (void)response;
    }

    void ListCommissionItems(::google::protobuf::RpcController* controller,
              const ListCommissionItemsRequest* request,
              ListCommissionItemsResponse* response,
              ::google::protobuf::Closure* done) override {
        brpc::ClosureGuard done_guard(done);
        (void)controller;
        (void)request;
        (void)response;
    }

};

}
}

int main(int argc, char* argv[]) {
    GFLAGS_NAMESPACE::ParseCommandLineFlags(&argc, &argv, true);
    brpc::Server server;
    simple_living::tracking_domain::TrackingLinkServiceImpl g_trackingLinkServiceImpl;
    if (server.AddService(&g_trackingLinkServiceImpl, brpc::SERVER_DOESNT_OWN_SERVICE) != 0) {
        LOG(ERROR) << "Fail to add service";
        return 1;
    }
    simple_living::tracking_domain::TrackingRedirectServiceImpl g_trackingRedirectServiceImpl;
    if (server.AddService(&g_trackingRedirectServiceImpl, brpc::SERVER_DOESNT_OWN_SERVICE) != 0) {
        LOG(ERROR) << "Fail to add service";
        return 1;
    }
    simple_living::tracking_domain::TrackingClickServiceImpl g_trackingClickServiceImpl;
    if (server.AddService(&g_trackingClickServiceImpl, brpc::SERVER_DOESNT_OWN_SERVICE) != 0) {
        LOG(ERROR) << "Fail to add service";
        return 1;
    }
    simple_living::tracking_domain::TrackingConversionServiceImpl g_trackingConversionServiceImpl;
    if (server.AddService(&g_trackingConversionServiceImpl, brpc::SERVER_DOESNT_OWN_SERVICE) != 0) {
        LOG(ERROR) << "Fail to add service";
        return 1;
    }
    simple_living::tracking_domain::TrackingCommissionViewServiceImpl g_trackingCommissionViewServiceImpl;
    if (server.AddService(&g_trackingCommissionViewServiceImpl, brpc::SERVER_DOESNT_OWN_SERVICE) != 0) {
        LOG(ERROR) << "Fail to add service";
        return 1;
    }
    brpc::ServerOptions options;
    if (server.Start(FLAGS_port, &options) != 0) {
        LOG(ERROR) << "Fail to start server";
        return 1;
    }
    server.RunUntilAskedToQuit();
    return 0;
}
