// GENERATED by tools/generate_brpc_stub_server.py — replace with real logic.
// content-domain
#include <gflags/gflags.h>
#include <brpc/server.h>
#include <butil/logging.h>

#include "content_domain.pb.h"

DEFINE_int32(port, 9102, "TCP port for this brpc server");

namespace simple_living {
namespace content_domain {

class ContentServiceImpl : public ContentService {
public:
    void ListThemes(::google::protobuf::RpcController* controller,
              const ListThemesRequest* request,
              ListThemesResponse* response,
              ::google::protobuf::Closure* done) override {
        brpc::ClosureGuard done_guard(done);
        (void)controller;
        (void)request;
        (void)response;
    }

    void GetThemeDetail(::google::protobuf::RpcController* controller,
              const GetThemeDetailRequest* request,
              GetThemeDetailResponse* response,
              ::google::protobuf::Closure* done) override {
        brpc::ClosureGuard done_guard(done);
        (void)controller;
        (void)request;
        (void)response;
    }

    void BatchGetGuideCards(::google::protobuf::RpcController* controller,
              const BatchGetGuideCardsRequest* request,
              BatchGetGuideCardsResponse* response,
              ::google::protobuf::Closure* done) override {
        brpc::ClosureGuard done_guard(done);
        (void)controller;
        (void)request;
        (void)response;
    }

    void ListGuideCards(::google::protobuf::RpcController* controller,
              const ListGuideCardsRequest* request,
              ListGuideCardsResponse* response,
              ::google::protobuf::Closure* done) override {
        brpc::ClosureGuard done_guard(done);
        (void)controller;
        (void)request;
        (void)response;
    }

    void GetEditorialContent(::google::protobuf::RpcController* controller,
              const GetEditorialContentRequest* request,
              GetEditorialContentResponse* response,
              ::google::protobuf::Closure* done) override {
        brpc::ClosureGuard done_guard(done);
        (void)controller;
        (void)request;
        (void)response;
    }

    void ListEditorialContents(::google::protobuf::RpcController* controller,
              const ListEditorialContentsRequest* request,
              ListEditorialContentsResponse* response,
              ::google::protobuf::Closure* done) override {
        brpc::ClosureGuard done_guard(done);
        (void)controller;
        (void)request;
        (void)response;
    }

    void GetTopic(::google::protobuf::RpcController* controller,
              const GetTopicRequest* request,
              GetTopicResponse* response,
              ::google::protobuf::Closure* done) override {
        brpc::ClosureGuard done_guard(done);
        (void)controller;
        (void)request;
        (void)response;
    }

    void ListTopics(::google::protobuf::RpcController* controller,
              const ListTopicsRequest* request,
              ListTopicsResponse* response,
              ::google::protobuf::Closure* done) override {
        brpc::ClosureGuard done_guard(done);
        (void)controller;
        (void)request;
        (void)response;
    }

    void GetRankingList(::google::protobuf::RpcController* controller,
              const GetRankingListRequest* request,
              GetRankingListResponse* response,
              ::google::protobuf::Closure* done) override {
        brpc::ClosureGuard done_guard(done);
        (void)controller;
        (void)request;
        (void)response;
    }

    void ListRankingLists(::google::protobuf::RpcController* controller,
              const ListRankingListsRequest* request,
              ListRankingListsResponse* response,
              ::google::protobuf::Closure* done) override {
        brpc::ClosureGuard done_guard(done);
        (void)controller;
        (void)request;
        (void)response;
    }

    void UpsertGuideCard(::google::protobuf::RpcController* controller,
              const UpsertGuideCardRequest* request,
              UpsertGuideCardResponse* response,
              ::google::protobuf::Closure* done) override {
        brpc::ClosureGuard done_guard(done);
        (void)controller;
        (void)request;
        (void)response;
    }

    void UpsertEditorialContent(::google::protobuf::RpcController* controller,
              const UpsertEditorialContentRequest* request,
              UpsertEditorialContentResponse* response,
              ::google::protobuf::Closure* done) override {
        brpc::ClosureGuard done_guard(done);
        (void)controller;
        (void)request;
        (void)response;
    }

    void UpsertTopic(::google::protobuf::RpcController* controller,
              const UpsertTopicRequest* request,
              UpsertTopicResponse* response,
              ::google::protobuf::Closure* done) override {
        brpc::ClosureGuard done_guard(done);
        (void)controller;
        (void)request;
        (void)response;
    }

    void UpsertRankingList(::google::protobuf::RpcController* controller,
              const UpsertRankingListRequest* request,
              UpsertRankingListResponse* response,
              ::google::protobuf::Closure* done) override {
        brpc::ClosureGuard done_guard(done);
        (void)controller;
        (void)request;
        (void)response;
    }

    void SubmitForReview(::google::protobuf::RpcController* controller,
              const SubmitForReviewRequest* request,
              SubmitForReviewResponse* response,
              ::google::protobuf::Closure* done) override {
        brpc::ClosureGuard done_guard(done);
        (void)controller;
        (void)request;
        (void)response;
    }

    void PublishRevision(::google::protobuf::RpcController* controller,
              const PublishRevisionRequest* request,
              PublishRevisionResponse* response,
              ::google::protobuf::Closure* done) override {
        brpc::ClosureGuard done_guard(done);
        (void)controller;
        (void)request;
        (void)response;
    }

};

}
}

int main(int argc, char* argv[]) {
    GFLAGS_NAMESPACE::ParseCommandLineFlags(&argc, &argv, true);
    brpc::Server server;
    simple_living::content_domain::ContentServiceImpl g_contentServiceImpl;
    if (server.AddService(&g_contentServiceImpl, brpc::SERVER_DOESNT_OWN_SERVICE) != 0) {
        LOG(ERROR) << "Fail to add service";
        return 1;
    }
    brpc::ServerOptions options;
    if (server.Start(FLAGS_port, &options) != 0) {
        LOG(ERROR) << "Fail to start server";
        return 1;
    }
    server.RunUntilAskedToQuit();
    return 0;
}
