apiVersion: v1
kind: Service
metadata:
  name: tracking-domain
  namespace: simple-living
  annotations:
    simple-living.io/internal-dns: "tracking-domain.simple-living.svc.cluster.local"
spec:
  type: ClusterIP
  selector:
    app: tracking-domain
  ports:
    - name: grpc
      protocol: TCP
      port: 9105
      targetPort: 9105
