// GENERATED by tools/generate_brpc_stub_server.py — replace with real logic.
// governance-domain
#include <gflags/gflags.h>
#include <brpc/server.h>
#include <butil/logging.h>

#include "governance_domain.pb.h"

DEFINE_int32(port, 9106, "TCP port for this brpc server");

namespace simple_living {
namespace governance_domain {

class GovernanceReviewServiceImpl : public GovernanceReviewService {
public:
    void EnqueueReview(::google::protobuf::RpcController* controller,
              const EnqueueReviewRequest* request,
              EnqueueReviewResponse* response,
              ::google::protobuf::Closure* done) override {
        brpc::ClosureGuard done_guard(done);
        (void)controller;
        (void)request;
        (void)response;
    }

    void ListReviewQueueItems(::google::protobuf::RpcController* controller,
              const ListReviewQueueItemsRequest* request,
              ListReviewQueueItemsResponse* response,
              ::google::protobuf::Closure* done) override {
        brpc::ClosureGuard done_guard(done);
        (void)controller;
        (void)request;
        (void)response;
    }

    void SubmitReviewDecision(::google::protobuf::RpcController* controller,
              const SubmitReviewDecisionRequest* request,
              SubmitReviewDecisionResponse* response,
              ::google::protobuf::Closure* done) override {
        brpc::ClosureGuard done_guard(done);
        (void)controller;
        (void)request;
        (void)response;
    }

    void ListReviewDecisions(::google::protobuf::RpcController* controller,
              const ListReviewDecisionsRequest* request,
              ListReviewDecisionsResponse* response,
              ::google::protobuf::Closure* done) override {
        brpc::ClosureGuard done_guard(done);
        (void)controller;
        (void)request;
        (void)response;
    }

    void GetReviewState(::google::protobuf::RpcController* controller,
              const GetReviewStateRequest* request,
              GetReviewStateResponse* response,
              ::google::protobuf::Closure* done) override {
        brpc::ClosureGuard done_guard(done);
        (void)controller;
        (void)request;
        (void)response;
    }

};

class GovernanceCooperationServiceImpl : public GovernanceCooperationService {
public:
    void UpsertCooperationLabel(::google::protobuf::RpcController* controller,
              const UpsertCooperationLabelRequest* request,
              UpsertCooperationLabelResponse* response,
              ::google::protobuf::Closure* done) override {
        brpc::ClosureGuard done_guard(done);
        (void)controller;
        (void)request;
        (void)response;
    }

    void BatchGetCooperationLabels(::google::protobuf::RpcController* controller,
              const BatchGetCooperationLabelsRequest* request,
              BatchGetCooperationLabelsResponse* response,
              ::google::protobuf::Closure* done) override {
        brpc::ClosureGuard done_guard(done);
        (void)controller;
        (void)request;
        (void)response;
    }

    void ListDisclosureTemplates(::google::protobuf::RpcController* controller,
              const ListDisclosureTemplatesRequest* request,
              ListDisclosureTemplatesResponse* response,
              ::google::protobuf::Closure* done) override {
        brpc::ClosureGuard done_guard(done);
        (void)controller;
        (void)request;
        (void)response;
    }

};

class GovernanceVisibilityServiceImpl : public GovernanceVisibilityService {
public:
    void SetVisibilityVerdict(::google::protobuf::RpcController* controller,
              const SetVisibilityVerdictRequest* request,
              SetVisibilityVerdictResponse* response,
              ::google::protobuf::Closure* done) override {
        brpc::ClosureGuard done_guard(done);
        (void)controller;
        (void)request;
        (void)response;
    }

    void BatchSetVisibilityVerdict(::google::protobuf::RpcController* controller,
              const BatchSetVisibilityVerdictRequest* request,
              BatchSetVisibilityVerdictResponse* response,
              ::google::protobuf::Closure* done) override {
        brpc::ClosureGuard done_guard(done);
        (void)controller;
        (void)request;
        (void)response;
    }

    void GetVisibilityVerdict(::google::protobuf::RpcController* controller,
              const GetVisibilityVerdictRequest* request,
              GetVisibilityVerdictResponse* response,
              ::google::protobuf::Closure* done) override {
        brpc::ClosureGuard done_guard(done);
        (void)controller;
        (void)request;
        (void)response;
    }

    void EvaluateVisibility(::google::protobuf::RpcController* controller,
              const EvaluateVisibilityRequest* request,
              EvaluateVisibilityResponse* response,
              ::google::protobuf::Closure* done) override {
        brpc::ClosureGuard done_guard(done);
        (void)controller;
        (void)request;
        (void)response;
    }

};

class GovernanceOpsConfigServiceImpl : public GovernanceOpsConfigService {
public:
    void GetOpsConfigSnapshot(::google::protobuf::RpcController* controller,
              const GetOpsConfigSnapshotRequest* request,
              GetOpsConfigSnapshotResponse* response,
              ::google::protobuf::Closure* done) override {
        brpc::ClosureGuard done_guard(done);
        (void)controller;
        (void)request;
        (void)response;
    }

    void CreateOpsConfigDraft(::google::protobuf::RpcController* controller,
              const CreateOpsConfigDraftRequest* request,
              CreateOpsConfigDraftResponse* response,
              ::google::protobuf::Closure* done) override {
        brpc::ClosureGuard done_guard(done);
        (void)controller;
        (void)request;
        (void)response;
    }

    void ReleaseOpsConfig(::google::protobuf::RpcController* controller,
              const ReleaseOpsConfigRequest* request,
              ReleaseOpsConfigResponse* response,
              ::google::protobuf::Closure* done) override {
        brpc::ClosureGuard done_guard(done);
        (void)controller;
        (void)request;
        (void)response;
    }

    void RollbackOpsConfigRelease(::google::protobuf::RpcController* controller,
              const RollbackOpsConfigReleaseRequest* request,
              RollbackOpsConfigReleaseResponse* response,
              ::google::protobuf::Closure* done) override {
        brpc::ClosureGuard done_guard(done);
        (void)controller;
        (void)request;
        (void)response;
    }

};

class GovernanceRiskServiceImpl : public GovernanceRiskService {
public:
    void CreateRiskFlag(::google::protobuf::RpcController* controller,
              const CreateRiskFlagRequest* request,
              CreateRiskFlagResponse* response,
              ::google::protobuf::Closure* done) override {
        brpc::ClosureGuard done_guard(done);
        (void)controller;
        (void)request;
        (void)response;
    }

    void RevokeRiskFlag(::google::protobuf::RpcController* controller,
              const RevokeRiskFlagRequest* request,
              RevokeRiskFlagResponse* response,
              ::google::protobuf::Closure* done) override {
        brpc::ClosureGuard done_guard(done);
        (void)controller;
        (void)request;
        (void)response;
    }

    void ListRiskFlags(::google::protobuf::RpcController* controller,
              const ListRiskFlagsRequest* request,
              ListRiskFlagsResponse* response,
              ::google::protobuf::Closure* done) override {
        brpc::ClosureGuard done_guard(done);
        (void)controller;
        (void)request;
        (void)response;
    }

    void BatchGetRiskFlagsBySubject(::google::protobuf::RpcController* controller,
              const BatchGetRiskFlagsBySubjectRequest* request,
              BatchGetRiskFlagsBySubjectResponse* response,
              ::google::protobuf::Closure* done) override {
        brpc::ClosureGuard done_guard(done);
        (void)controller;
        (void)request;
        (void)response;
    }

};

class GovernancePolicyServiceImpl : public GovernancePolicyService {
public:
    void EvaluatePolicy(::google::protobuf::RpcController* controller,
              const EvaluatePolicyRequest* request,
              EvaluatePolicyResponse* response,
              ::google::protobuf::Closure* done) override {
        brpc::ClosureGuard done_guard(done);
        (void)controller;
        (void)request;
        (void)response;
    }

    void CreatePolicyVersion(::google::protobuf::RpcController* controller,
              const CreatePolicyVersionRequest* request,
              CreatePolicyVersionResponse* response,
              ::google::protobuf::Closure* done) override {
        brpc::ClosureGuard done_guard(done);
        (void)controller;
        (void)request;
        (void)response;
    }

    void SimulatePolicy(::google::protobuf::RpcController* controller,
              const SimulatePolicyRequest* request,
              SimulatePolicyResponse* response,
              ::google::protobuf::Closure* done) override {
        brpc::ClosureGuard done_guard(done);
        (void)controller;
        (void)request;
        (void)response;
    }

};

}
}

int main(int argc, char* argv[]) {
    GFLAGS_NAMESPACE::ParseCommandLineFlags(&argc, &argv, true);
    brpc::Server server;
    simple_living::governance_domain::GovernanceReviewServiceImpl g_governanceReviewServiceImpl;
    if (server.AddService(&g_governanceReviewServiceImpl, brpc::SERVER_DOESNT_OWN_SERVICE) != 0) {
        LOG(ERROR) << "Fail to add service";
        return 1;
    }
    simple_living::governance_domain::GovernanceCooperationServiceImpl g_governanceCooperationServiceImpl;
    if (server.AddService(&g_governanceCooperationServiceImpl, brpc::SERVER_DOESNT_OWN_SERVICE) != 0) {
        LOG(ERROR) << "Fail to add service";
        return 1;
    }
    simple_living::governance_domain::GovernanceVisibilityServiceImpl g_governanceVisibilityServiceImpl;
    if (server.AddService(&g_governanceVisibilityServiceImpl, brpc::SERVER_DOESNT_OWN_SERVICE) != 0) {
        LOG(ERROR) << "Fail to add service";
        return 1;
    }
    simple_living::governance_domain::GovernanceOpsConfigServiceImpl g_governanceOpsConfigServiceImpl;
    if (server.AddService(&g_governanceOpsConfigServiceImpl, brpc::SERVER_DOESNT_OWN_SERVICE) != 0) {
        LOG(ERROR) << "Fail to add service";
        return 1;
    }
    simple_living::governance_domain::GovernanceRiskServiceImpl g_governanceRiskServiceImpl;
    if (server.AddService(&g_governanceRiskServiceImpl, brpc::SERVER_DOESNT_OWN_SERVICE) != 0) {
        LOG(ERROR) << "Fail to add service";
        return 1;
    }
    simple_living::governance_domain::GovernancePolicyServiceImpl g_governancePolicyServiceImpl;
    if (server.AddService(&g_governancePolicyServiceImpl, brpc::SERVER_DOESNT_OWN_SERVICE) != 0) {
        LOG(ERROR) << "Fail to add service";
        return 1;
    }
    brpc::ServerOptions options;
    if (server.Start(FLAGS_port, &options) != 0) {
        LOG(ERROR) << "Fail to start server";
        return 1;
    }
    server.RunUntilAskedToQuit();
    return 0;
}
