apiVersion: v1
kind: Service
metadata:
  name: recommendation-domain
  namespace: simple-living
  annotations:
    simple-living.io/internal-dns: "recommendation-domain.simple-living.svc.cluster.local"
spec:
  type: ClusterIP
  selector:
    app: recommendation-domain
  ports:
    - name: grpc
      protocol: TCP
      port: 9103
      targetPort: 9103
