apiVersion: v1
kind: Service
metadata:
  name: governance-domain
  namespace: simple-living
  annotations:
    simple-living.io/internal-dns: "governance-domain.simple-living.svc.cluster.local"
spec:
  type: ClusterIP
  selector:
    app: governance-domain
  ports:
    - name: grpc
      protocol: TCP
      port: 9106
      targetPort: 9106
