// GENERATED by tools/generate_brpc_stub_server.py — replace with real logic.
// recommendation-domain
#include <gflags/gflags.h>
#include <brpc/server.h>
#include <butil/logging.h>

#include "recommendation_domain_service.pb.h"

DEFINE_int32(port, 9103, "TCP port for this brpc server");

namespace simple_living {
namespace recommendation_domain {

class RecommendationServiceImpl : public RecommendationService {
public:
    void QueryRecommendations(::google::protobuf::RpcController* controller,
              const QueryRecommendationsRequest* request,
              QueryRecommendationsResponse* response,
              ::google::protobuf::Closure* done) override {
        brpc::ClosureGuard done_guard(done);
        (void)controller;
        (void)request;
        (void)response;
    }

    void GetPopularRecommendations(::google::protobuf::RpcController* controller,
              const GetPopularRecommendationsRequest* request,
              GetPopularRecommendationsResponse* response,
              ::google::protobuf::Closure* done) override {
        brpc::ClosureGuard done_guard(done);
        (void)controller;
        (void)request;
        (void)response;
    }

    void ExplainRecommendations(::google::protobuf::RpcController* controller,
              const ExplainRecommendationsRequest* request,
              ExplainRecommendationsResponse* response,
              ::google::protobuf::Closure* done) override {
        brpc::ClosureGuard done_guard(done);
        (void)controller;
        (void)request;
        (void)response;
    }

    void HealthCheck(::google::protobuf::RpcController* controller,
              const HealthCheckRequest* request,
              HealthCheckResponse* response,
              ::google::protobuf::Closure* done) override {
        brpc::ClosureGuard done_guard(done);
        (void)controller;
        (void)request;
        (void)response;
    }

};

}
}

int main(int argc, char* argv[]) {
    GFLAGS_NAMESPACE::ParseCommandLineFlags(&argc, &argv, true);
    brpc::Server server;
    simple_living::recommendation_domain::RecommendationServiceImpl g_recommendationServiceImpl;
    if (server.AddService(&g_recommendationServiceImpl, brpc::SERVER_DOESNT_OWN_SERVICE) != 0) {
        LOG(ERROR) << "Fail to add service";
        return 1;
    }
    brpc::ServerOptions options;
    if (server.Start(FLAGS_port, &options) != 0) {
        LOG(ERROR) << "Fail to start server";
        return 1;
    }
    server.RunUntilAskedToQuit();
    return 0;
}
