// GENERATED by tools/generate_brpc_stub_server.py — replace with real logic.
// gateway-edge
#include <gflags/gflags.h>
#include <brpc/server.h>
#include <butil/logging.h>

#include "gateway_user_edge.pb.h"
#include "gateway_pages_edge.pb.h"

DEFINE_int32(port, 8080, "TCP port for this brpc server");

namespace simple_living {
namespace gateway {
namespace user {

class GatewayUserEdgeV2Impl : public GatewayUserEdgeV2 {
public:
    void PostGuestSession(::google::protobuf::RpcController* controller,
              const ::simple_living::user_domain::EnsureGuestSessionRequest* request,
              ::simple_living::user_domain::EnsureGuestSessionResponse* response,
              ::google::protobuf::Closure* done) override {
        brpc::ClosureGuard done_guard(done);
        (void)controller;
        (void)request;
        (void)response;
    }

    void PostAuthTokenIssue(::google::protobuf::RpcController* controller,
              const ::simple_living::user_domain::IssueTokenPairRequest* request,
              ::simple_living::user_domain::IssueTokenPairResponse* response,
              ::google::protobuf::Closure* done) override {
        brpc::ClosureGuard done_guard(done);
        (void)controller;
        (void)request;
        (void)response;
    }

    void PostAuthTokenRefresh(::google::protobuf::RpcController* controller,
              const RefreshTokenHttpRequest* request,
              ::simple_living::user_domain::IssueTokenPairResponse* response,
              ::google::protobuf::Closure* done) override {
        brpc::ClosureGuard done_guard(done);
        (void)controller;
        (void)request;
        (void)response;
    }

    void DeleteAuthSession(::google::protobuf::RpcController* controller,
              const ::simple_living::user_domain::RevokeSessionRequest* request,
              ::simple_living::user_domain::RevokeSessionResponse* response,
              ::google::protobuf::Closure* done) override {
        brpc::ClosureGuard done_guard(done);
        (void)controller;
        (void)request;
        (void)response;
    }

    void GetMeProfile(::google::protobuf::RpcController* controller,
              const ::simple_living::user_domain::GetProfileRequest* request,
              ::simple_living::user_domain::GetProfileResponse* response,
              ::google::protobuf::Closure* done) override {
        brpc::ClosureGuard done_guard(done);
        (void)controller;
        (void)request;
        (void)response;
    }

    void PatchMeProfile(::google::protobuf::RpcController* controller,
              const ::simple_living::user_domain::UpdateProfileRequest* request,
              ::simple_living::user_domain::UpdateProfileResponse* response,
              ::google::protobuf::Closure* done) override {
        brpc::ClosureGuard done_guard(done);
        (void)controller;
        (void)request;
        (void)response;
    }

    void GetMePreferences(::google::protobuf::RpcController* controller,
              const ::simple_living::user_domain::GetPreferencesRequest* request,
              ::simple_living::user_domain::GetPreferencesResponse* response,
              ::google::protobuf::Closure* done) override {
        brpc::ClosureGuard done_guard(done);
        (void)controller;
        (void)request;
        (void)response;
    }

    void PutMePreferences(::google::protobuf::RpcController* controller,
              const ::simple_living::user_domain::UpdatePreferencesRequest* request,
              ::simple_living::user_domain::UpdatePreferencesResponse* response,
              ::google::protobuf::Closure* done) override {
        brpc::ClosureGuard done_guard(done);
        (void)controller;
        (void)request;
        (void)response;
    }

    void GetMeFavorites(::google::protobuf::RpcController* controller,
              const ListFavoritesHttpRequest* request,
              ::simple_living::user_domain::ListFavoritesResponse* response,
              ::google::protobuf::Closure* done) override {
        brpc::ClosureGuard done_guard(done);
        (void)controller;
        (void)request;
        (void)response;
    }

    void PostMeFavorite(::google::protobuf::RpcController* controller,
              const AddFavoriteHttpRequest* request,
              ::simple_living::user_domain::AddFavoriteResponse* response,
              ::google::protobuf::Closure* done) override {
        brpc::ClosureGuard done_guard(done);
        (void)controller;
        (void)request;
        (void)response;
    }

    void DeleteMeFavorite(::google::protobuf::RpcController* controller,
              const RemoveFavoriteHttpRequest* request,
              ::simple_living::user_domain::RemoveFavoriteResponse* response,
              ::google::protobuf::Closure* done) override {
        brpc::ClosureGuard done_guard(done);
        (void)controller;
        (void)request;
        (void)response;
    }

    void GetMeHistory(::google::protobuf::RpcController* controller,
              const ListHistoryHttpRequest* request,
              ::simple_living::user_domain::ListHistoryResponse* response,
              ::google::protobuf::Closure* done) override {
        brpc::ClosureGuard done_guard(done);
        (void)controller;
        (void)request;
        (void)response;
    }

    void PostMeHistoryEvent(::google::protobuf::RpcController* controller,
              const RecordHistoryEventHttpRequest* request,
              ::simple_living::user_domain::RecordHistoryEventResponse* response,
              ::google::protobuf::Closure* done) override {
        brpc::ClosureGuard done_guard(done);
        (void)controller;
        (void)request;
        (void)response;
    }

    void DeleteMeHistory(::google::protobuf::RpcController* controller,
              const ClearHistoryHttpRequest* request,
              ::simple_living::user_domain::ClearHistoryResponse* response,
              ::google::protobuf::Closure* done) override {
        brpc::ClosureGuard done_guard(done);
        (void)controller;
        (void)request;
        (void)response;
    }

    void PostMeFeedback(::google::protobuf::RpcController* controller,
              const SubmitFeedbackHttpRequest* request,
              ::simple_living::user_domain::SubmitFeedbackResponse* response,
              ::google::protobuf::Closure* done) override {
        brpc::ClosureGuard done_guard(done);
        (void)controller;
        (void)request;
        (void)response;
    }

    void GetMeConsent(::google::protobuf::RpcController* controller,
              const ::simple_living::user_domain::GetConsentRequest* request,
              ::simple_living::user_domain::GetConsentResponse* response,
              ::google::protobuf::Closure* done) override {
        brpc::ClosureGuard done_guard(done);
        (void)controller;
        (void)request;
        (void)response;
    }

    void PutMeConsent(::google::protobuf::RpcController* controller,
              const ::simple_living::user_domain::UpdateConsentRequest* request,
              ::simple_living::user_domain::UpdateConsentResponse* response,
              ::google::protobuf::Closure* done) override {
        brpc::ClosureGuard done_guard(done);
        (void)controller;
        (void)request;
        (void)response;
    }

    void GetMeSummary(::google::protobuf::RpcController* controller,
              const ::simple_living::user_domain::GetMeSummaryRequest* request,
              ::simple_living::user_domain::GetMeSummaryResponse* response,
              ::google::protobuf::Closure* done) override {
        brpc::ClosureGuard done_guard(done);
        (void)controller;
        (void)request;
        (void)response;
    }

};

}
}
}

namespace simple_living {
namespace gateway {
namespace pages {

class GatewayPagesEdgeV2Impl : public GatewayPagesEdgeV2 {
public:
    void GetHomeFeed(::google::protobuf::RpcController* controller,
              const HomeFeedRequest* request,
              HomeFeedResponse* response,
              ::google::protobuf::Closure* done) override {
        brpc::ClosureGuard done_guard(done);
        (void)controller;
        (void)request;
        (void)response;
    }

    void GetGuideDetail(::google::protobuf::RpcController* controller,
              const GuideDetailRequest* request,
              GuideDetailResponse* response,
              ::google::protobuf::Closure* done) override {
        brpc::ClosureGuard done_guard(done);
        (void)controller;
        (void)request;
        (void)response;
    }

    void PrepareRedirect(::google::protobuf::RpcController* controller,
              const RedirectPrepareRequest* request,
              RedirectPrepareResponse* response,
              ::google::protobuf::Closure* done) override {
        brpc::ClosureGuard done_guard(done);
        (void)controller;
        (void)request;
        (void)response;
    }

    void GetMeSummary(::google::protobuf::RpcController* controller,
              const MeSummaryRequest* request,
              MeSummaryResponse* response,
              ::google::protobuf::Closure* done) override {
        brpc::ClosureGuard done_guard(done);
        (void)controller;
        (void)request;
        (void)response;
    }

};

}
}
}

int main(int argc, char* argv[]) {
    GFLAGS_NAMESPACE::ParseCommandLineFlags(&argc, &argv, true);
    brpc::Server server;
    simple_living::gateway::user::GatewayUserEdgeV2Impl g_gatewayUserEdgeV2Impl;
    if (server.AddService(&g_gatewayUserEdgeV2Impl, brpc::SERVER_DOESNT_OWN_SERVICE) != 0) {
        LOG(ERROR) << "Fail to add service";
        return 1;
    }
    simple_living::gateway::pages::GatewayPagesEdgeV2Impl g_gatewayPagesEdgeV2Impl;
    if (server.AddService(&g_gatewayPagesEdgeV2Impl, brpc::SERVER_DOESNT_OWN_SERVICE) != 0) {
        LOG(ERROR) << "Fail to add service";
        return 1;
    }
    brpc::ServerOptions options;
    if (server.Start(FLAGS_port, &options) != 0) {
        LOG(ERROR) << "Fail to start server";
        return 1;
    }
    server.RunUntilAskedToQuit();
    return 0;
}
