#!/usr/bin/env python3
"""Generate a minimal brpc server .cpp from proto2 service definitions (cc_generic_services)."""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path


@dataclass
class Rpc:
    name: str
    request: str
    response: str


@dataclass
class Service:
    name: str
    rpcs: list[Rpc]


@dataclass
class ProtoShard:
    path: Path
    stem: str


def _cpp_type(type_name: str) -> str:
    t = type_name.strip()
    if "." in t:
        return "::" + t.replace(".", "::")
    return t


def parse_proto(path: Path) -> tuple[str, list[Service]]:
    text = path.read_text(encoding="utf-8")
    m = re.search(r"^\s*package\s+([\w.]+)\s*;", text, re.MULTILINE)
    if not m:
        raise SystemExit(f"no package in {path}")
    package = m.group(1)
    services: list[Service] = []
    for sm in re.finditer(
        r"service\s+(\w+)\s*\{([^}]*)\}", text, re.MULTILINE | re.DOTALL
    ):
        sname = sm.group(1)
        body = sm.group(2)
        normalized = re.sub(r"\s+", " ", body)
        rpcs: list[Rpc] = []
        for rm in re.finditer(
            r"rpc\s+(\w+)\s*\(\s*([^)]+?)\s*\)\s*returns\s*\(\s*([^)]+?)\s*\)\s*;",
            normalized,
        ):
            rpcs.append(
                Rpc(
                    name=rm.group(1),
                    request=_cpp_type(rm.group(2)),
                    response=_cpp_type(rm.group(3)),
                )
            )
        if rpcs:
            services.append(Service(name=sname, rpcs=rpcs))
    if not services:
        raise SystemExit(f"no services parsed in {path}")
    return package, services


def _emit_cpp_multi(
    shards: list[tuple[ProtoShard, str, list[Service]]],
    port: int,
    binary_comment: str,
) -> str:
    out: list[str] = [
        "// GENERATED by tools/generate_brpc_stub_server.py — replace with real logic.",
        f"// {binary_comment}",
        '#include <gflags/gflags.h>',
        '#include <brpc/server.h>',
        '#include <butil/logging.h>',
        "",
    ]
    for shard, _, _ in shards:
        out.append(f'#include "{shard.stem}.pb.h"')
    out.append("")
    out.append(f"DEFINE_int32(port, {port}, \"TCP port for this brpc server\");")
    out.append("")

    for shard, package, services in shards:
        parts = package.split(".")
        for p in parts:
            out.append(f"namespace {p} {{")
        out.append("")
        for svc in services:
            impl = f"{svc.name}Impl"
            var = f"g_{impl[0].lower()}{impl[1:]}"
            out.append(f"class {impl} : public {svc.name} {{")
            out.append("public:")
            for r in svc.rpcs:
                out.append(
                    f"    void {r.name}(::google::protobuf::RpcController* controller,"
                )
                out.append(f"              const {r.request}* request,")
                out.append(f"              {r.response}* response,")
                out.append(
                    "              ::google::protobuf::Closure* done) override {"
                )
                out.append("        brpc::ClosureGuard done_guard(done);")
                out.append("        (void)controller;")
                out.append("        (void)request;")
                out.append("        (void)response;")
                out.append("    }")
                out.append("")
            out.append("};")
            out.append("")
        for _ in parts:
            out.append("}")
        out.append("")

    impl_entries_fixed: list[tuple[str, str]] = []
    for shard, package, services in shards:
        ns = "::".join(package.split("."))
        for svc in services:
            impl = f"{svc.name}Impl"
            var = f"g_{impl[0].lower()}{impl[1:]}"
            impl_entries_fixed.append((f"{ns}::{impl}", var))

    out.append("int main(int argc, char* argv[]) {")
    out.append("    GFLAGS_NAMESPACE::ParseCommandLineFlags(&argc, &argv, true);")
    out.append("    brpc::Server server;")
    for qname, var in impl_entries_fixed:
        out.append(f"    {qname} {var};")
        out.append(
            f"    if (server.AddService(&{var}, brpc::SERVER_DOESNT_OWN_SERVICE) != 0) {{"
        )
        out.append('        LOG(ERROR) << "Fail to add service";')
        out.append("        return 1;")
        out.append("    }")
    out.append("    brpc::ServerOptions options;")
    out.append("    if (server.Start(FLAGS_port, &options) != 0) {")
    out.append('        LOG(ERROR) << "Fail to start server";')
    out.append("        return 1;")
    out.append("    }")
    out.append("    server.RunUntilAskedToQuit();")
    out.append("    return 0;")
    out.append("}")
    out.append("")
    return "\n".join(out)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "-s",
        "--shard",
        action="append",
        required=True,
        metavar="PROTO:STEM",
        help="Proto path and .pb.h stem, e.g. services/foo/proto/bar.proto:bar",
    )
    ap.add_argument("-o", "--output", type=Path, required=True)
    ap.add_argument("--port", type=int, required=True)
    ap.add_argument("--comment", default="")
    args = ap.parse_args()

    parsed: list[tuple[ProtoShard, str, list[Service]]] = []
    for raw in args.shard:
        if ":" not in raw:
            raise SystemExit(f"bad --shard {raw!r}, want path:stem")
        pth, stem = raw.rsplit(":", 1)
        path = Path(pth)
        shard = ProtoShard(path=path, stem=stem)
        package, services = parse_proto(path)
        parsed.append((shard, package, services))

    text = _emit_cpp_multi(
        parsed,
        args.port,
        args.comment or "multi-shard stub server",
    )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(text, encoding="utf-8")
    print(f"wrote {args.output}", file=sys.stderr)


if __name__ == "__main__":
    main()
