// GENERATED by tools/generate_brpc_stub_server.py — replace with real logic.
// affiliate-domain
#include <gflags/gflags.h>
#include <brpc/server.h>
#include <butil/logging.h>

#include "affiliate_domain.pb.h"

DEFINE_int32(port, 9104, "TCP port for this brpc server");

namespace simple_living {
namespace affiliate_domain {

class AffiliatePartnerServiceImpl : public AffiliatePartnerService {
public:
    void GetPartnerCapabilitySnapshot(::google::protobuf::RpcController* controller,
              const GetPartnerCapabilitySnapshotRequest* request,
              GetPartnerCapabilitySnapshotResponse* response,
              ::google::protobuf::Closure* done) override {
        brpc::ClosureGuard done_guard(done);
        (void)controller;
        (void)request;
        (void)response;
    }

    void ValidateLinkGenerationInput(::google::protobuf::RpcController* controller,
              const ValidateLinkGenerationInputRequest* request,
              ValidateLinkGenerationInputResponse* response,
              ::google::protobuf::Closure* done) override {
        brpc::ClosureGuard done_guard(done);
        (void)controller;
        (void)request;
        (void)response;
    }

};

class AffiliateCommissionRuleServiceImpl : public AffiliateCommissionRuleService {
public:
    void CreateCommissionRuleSetVersion(::google::protobuf::RpcController* controller,
              const CreateCommissionRuleSetVersionRequest* request,
              CreateCommissionRuleSetVersionResponse* response,
              ::google::protobuf::Closure* done) override {
        brpc::ClosureGuard done_guard(done);
        (void)controller;
        (void)request;
        (void)response;
    }

    void GetCommissionRuleSet(::google::protobuf::RpcController* controller,
              const GetCommissionRuleSetRequest* request,
              GetCommissionRuleSetResponse* response,
              ::google::protobuf::Closure* done) override {
        brpc::ClosureGuard done_guard(done);
        (void)controller;
        (void)request;
        (void)response;
    }

};

class AffiliateIntakeServiceImpl : public AffiliateIntakeService {
public:
    void IngestPartnerWebhook(::google::protobuf::RpcController* controller,
              const IngestPartnerWebhookRequest* request,
              IngestPartnerWebhookResponse* response,
              ::google::protobuf::Closure* done) override {
        brpc::ClosureGuard done_guard(done);
        (void)controller;
        (void)request;
        (void)response;
    }

    void RegisterReportBatch(::google::protobuf::RpcController* controller,
              const RegisterReportBatchRequest* request,
              RegisterReportBatchResponse* response,
              ::google::protobuf::Closure* done) override {
        brpc::ClosureGuard done_guard(done);
        (void)controller;
        (void)request;
        (void)response;
    }

};

}
}

int main(int argc, char* argv[]) {
    GFLAGS_NAMESPACE::ParseCommandLineFlags(&argc, &argv, true);
    brpc::Server server;
    simple_living::affiliate_domain::AffiliatePartnerServiceImpl g_affiliatePartnerServiceImpl;
    if (server.AddService(&g_affiliatePartnerServiceImpl, brpc::SERVER_DOESNT_OWN_SERVICE) != 0) {
        LOG(ERROR) << "Fail to add service";
        return 1;
    }
    simple_living::affiliate_domain::AffiliateCommissionRuleServiceImpl g_affiliateCommissionRuleServiceImpl;
    if (server.AddService(&g_affiliateCommissionRuleServiceImpl, brpc::SERVER_DOESNT_OWN_SERVICE) != 0) {
        LOG(ERROR) << "Fail to add service";
        return 1;
    }
    simple_living::affiliate_domain::AffiliateIntakeServiceImpl g_affiliateIntakeServiceImpl;
    if (server.AddService(&g_affiliateIntakeServiceImpl, brpc::SERVER_DOESNT_OWN_SERVICE) != 0) {
        LOG(ERROR) << "Fail to add service";
        return 1;
    }
    brpc::ServerOptions options;
    if (server.Start(FLAGS_port, &options) != 0) {
        LOG(ERROR) << "Fail to start server";
        return 1;
    }
    server.RunUntilAskedToQuit();
    return 0;
}
